-- govdata_seed_demo_v1.sql
-- 12 synthetic visitor_intake rows for GovData demo / development.
-- Sprint 32 — remove or gate behind env flag before production.

INSERT INTO visitor_intake (session_id, passport_country, country_of_residence, age_band, trip_duration_band, travel_history, financial_confidence, employment_status, documentation_readiness, accommodation_type, return_travel_booked, travel_companions, derived_signals, created_at)
VALUES
    (gen_random_uuid(), 'India', 'India', '25-34', '1-3 months', 'first_time_traveller', 'not_sure', 'employed', 'some', 'hotel', true, 'partner', '{"financial_risk_flag":true,"intent_risk_proxy":true,"documentation_gap_flag":false,"strong_profile_indicator":false}', now() - interval '5 days'),
    (gen_random_uuid(), 'India', 'India', '35-44', '<1 month', 'some_travel', 'yes', 'self_employed', 'most_ready', 'hotel', true, 'family', '{"financial_risk_flag":false,"intent_risk_proxy":false,"documentation_gap_flag":false,"strong_profile_indicator":true}', now() - interval '4 days'),
    (gen_random_uuid(), 'India', 'India', '25-34', '1-3 months', 'first_time_traveller', 'no', 'between_jobs', 'none', 'not_sure', false, 'solo', '{"financial_risk_flag":true,"intent_risk_proxy":true,"documentation_gap_flag":true,"strong_profile_indicator":false}', now() - interval '3 days'),
    (gen_random_uuid(), 'India', 'India', '18-24', '<1 month', 'some_travel', 'not_sure', 'student', 'some', 'family_or_friends', false, 'solo', '{"financial_risk_flag":true,"intent_risk_proxy":false,"documentation_gap_flag":false,"strong_profile_indicator":false}', now() - interval '2 days'),
    (gen_random_uuid(), 'India', 'India', '45-54', '<1 month', 'frequent_traveller', 'yes', 'employed', 'most_ready', 'hotel', true, 'partner', '{"financial_risk_flag":false,"intent_risk_proxy":false,"documentation_gap_flag":false,"strong_profile_indicator":true}', now() - interval '1 day'),
    (gen_random_uuid(), 'China', 'China', '35-44', '3+ months', 'some_travel', 'not_sure', 'employed', 'some', 'mixed', true, 'family', '{"financial_risk_flag":true,"intent_risk_proxy":false,"documentation_gap_flag":false,"strong_profile_indicator":false}', now() - interval '6 days'),
    (gen_random_uuid(), 'China', 'China', '25-34', '1-3 months', 'first_time_traveller', 'yes', 'employed', 'most_ready', 'hotel', true, 'solo', '{"financial_risk_flag":false,"intent_risk_proxy":false,"documentation_gap_flag":false,"strong_profile_indicator":true}', now() - interval '4 days'),
    (gen_random_uuid(), 'Philippines', 'Philippines', '25-34', '<1 month', 'first_time_traveller', 'no', 'not_working', 'none', 'family_or_friends', false, 'solo', '{"financial_risk_flag":true,"intent_risk_proxy":true,"documentation_gap_flag":true,"strong_profile_indicator":false}', now() - interval '7 days'),
    (gen_random_uuid(), 'Philippines', 'Philippines', '18-24', '<1 month', 'some_travel', 'not_sure', 'employed', 'some', 'family_or_friends', true, 'family', '{"financial_risk_flag":true,"intent_risk_proxy":false,"documentation_gap_flag":false,"strong_profile_indicator":false}', now() - interval '2 days'),
    (gen_random_uuid(), 'United Kingdom', 'United Kingdom', '35-44', '1-3 months', 'frequent_traveller', 'yes', 'self_employed', 'most_ready', 'hotel', true, 'partner', '{"financial_risk_flag":false,"intent_risk_proxy":false,"documentation_gap_flag":false,"strong_profile_indicator":true}', now() - interval '3 days'),
    (gen_random_uuid(), 'United States', 'United States', '25-34', '1-3 months', 'frequent_traveller', 'yes', 'employed', 'most_ready', 'hotel', true, 'solo', '{"financial_risk_flag":false,"intent_risk_proxy":false,"documentation_gap_flag":false,"strong_profile_indicator":true}', now() - interval '1 day'),
    (gen_random_uuid(), 'Nepal', 'Nepal', '25-34', '3+ months', 'first_time_traveller', 'no', 'between_jobs', 'none', 'not_sure', false, 'solo', '{"financial_risk_flag":true,"intent_risk_proxy":true,"documentation_gap_flag":true,"strong_profile_indicator":false}', now() - interval '5 days');
